# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  link_0:
    - "center": [0.015, 0.011, 0.075]
      "radius": 0.08252
  link_1:
    - "center": [-0.01, -0.035, 0.066]
      "radius": 0.06439
    - "center": [0.002, -0.06, 0.168]
      "radius": 0.06361
    - "center": [-0.006, -0.057, 0.228]
      "radius": 0.05665
  link_2:
    - "center": [0.001, 0.075, -0.007]
      "radius": 0.07645
    - "center": [0.004, 0.067, 0.06]
      "radius": 0.06656
    - "center": [-0.004, 0.036, 0.148]
      "radius": 0.0559
    - "center": [0.019, 0.034, 0.149]
      "radius": 0.05438
  link_3:
    - "center": [-0.002, 0.006, 0.031]
      "radius": 0.06728
    - "center": [-0.001, 0.063, 0.179]
      "radius": 0.06151
    - "center": [-0.005, 0.053, 0.132]
      "radius": 0.06007
  link_4:
    - "center": [0.001, -0.065, 0.008]
      "radius": 0.06711
    - "center": [-0.004, -0.041, 0.127]
      "radius": 0.05787
    - "center": [-0.001, -0.064, 0.049]
      "radius": 0.06381
    - "center": [-0.004, -0.061, -0.006]
      "radius": 0.06381
    - "center": [0.021, -0.014, 0.14]
      "radius": 0.04467
  link_5:
    - "center": [0.028, -0.001, 0.026]
      "radius": 0.04917
    - "center": [-0.009, -0.031, 0.048]
      "radius": 0.04713
    - "center": [-0.032, 0.01, 0.037]
      "radius": 0.03554
  link_6:
    - "center": [-0.002, 0.074, -0.014]
      "radius": 0.07201
    - "center": [0.003, 0.074, 0.015]
      "radius": 0.06512
    - "center": [0.007, 0.085, -0.032]
      "radius": 0.06118
    - "center": [-0.009, 0.055, 0.025]
      "radius": 0.05528
    - "center": [0.014, 0.06, 0.009]
      "radius": 0.0602
  link_7:
    - "center": [0.004, 0.002, 0.005]
      "radius": 0.03398
    - "center": [0.006, -0.025, 0.008]
      "radius": 0.02794
    - "center": [-0.025, -0.003, 0.007]
      "radius": 0.02733
