# The robot description defines the generalized coordinates and how to map those
# to the underlying URDF dofs.

# Lula uses collision spheres to define the robot geometry in order to avoid
# collisions with external obstacles.  If no spheres are specified, Lula will
# not be able to avoid obstacles.

collision_spheres:
  link_base:
    - "center": [0.0, 0.0, 0.1]
      "radius": 0.05706
    - "center": [-0.0, 0.0, 0.049]
      "radius": 0.05706
  link1:
    - "center": [0.0, -0.004, -0.001]
      "radius": 0.05797
    - "center": [-0.002, -0.011, -0.074]
      "radius": 0.04645
    - "center": [0.001, 0.025, 0.001]
      "radius": 0.0562
  link2:
    - "center": [-0.001, -0.107, 0.011]
      "radius": 0.05519
    - "center": [-0.001, -0.111, 0.074]
      "radius": 0.05342
    - "center": [0.0, -0.147, -0.0]
      "radius": 0.05166
    - "center": [0.002, -0.008, 0.097]
      "radius": 0.03162
    - "center": [-0.005, -0.046, 0.097]
      "radius": 0.03103
  link3:
    - "center": [0.052, -0.015, 0.001]
      "radius": 0.05116
    - "center": [0.05, 0.023, 0.002]
      "radius": 0.05022
    - "center": [0.003, 0.015, -0.061]
      "radius": 0.04275
  link4:
    - "center": [0.077, -0.12, -0.0]
      "radius": 0.052
    - "center": [0.08, -0.082, 0.06]
      "radius": 0.04962
    - "center": [0.078, -0.087, -0.001]
      "radius": 0.05141
    - "center": [0.016, -0.017, 0.087]
      "radius": 0.02942
    - "center": [0.002, 0.017, 0.086]
      "radius": 0.02883
    - "center": [0.078, -0.083, 0.044]
      "radius": 0.05141
    - "center": [0.044, -0.048, 0.088]
      "radius": 0.02823
  link5:
    - "center": [0.0, 0.042, 0.0]
      "radius": 0.04692
    - "center": [0.005, 0.014, -0.145]
      "radius": 0.03782
    - "center": [-0.013, -0.012, -0.149]
      "radius": 0.03326
    - "center": [0.016, -0.011, -0.149]
      "radius": 0.03276
    - "center": [-0.0, 0.049, -0.001]
      "radius": 0.04642
    - "center": [-0.005, 0.04, -0.118]
      "radius": 0.02567
    - "center": [-0.018, 0.004, -0.145]
      "radius": 0.03377
    - "center": [0.001, 0.065, -0.087]
      "radius": 0.02365
    - "center": [0.002, 0.073, -0.049]
      "radius": 0.02314
    - "center": [0.017, 0.045, -0.112]
      "radius": 0.02264
  link6:
    - "center": [0.077, 0.012, -0.0]
      "radius": 0.04635
    - "center": [-0.003, -0.003, 0.026]
      "radius": 0.03992
    - "center": [0.075, 0.033, 0.002]
      "radius": 0.04555
    - "center": [0.035, 0.001, 0.021]
      "radius": 0.0351
    - "center": [0.074, 0.001, 0.001]
      "radius": 0.04555
  link7:
    - "center": [0.02, 0.003, -0.013]
      "radius": 0.023
    - "center": [-0.018, 0.017, -0.014]
      "radius": 0.023
    - "center": [0.004, -0.024, -0.013]
      "radius": 0.023
    - "center": [-0.022, -0.01, -0.013]
      "radius": 0.023
    - "center": [0.007, 0.023, -0.013]
      "radius": 0.023
